name: MineCoinsPlayersAPI
main: me.thomasrba.minecoinsplayersapi.MineCoinsPlayersAPI
version: 1.0
api-version: 1.20
commands:
  getStates:
    description: test
    permission-message: test
    permission: test.test
  setRank:
    description: set le grade
    permission-message: Pas le droit
    permission: admin.setrank